spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookstore-db
    username: bookstoreadmin
    password: bookstorepassword
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
      show-sql: true

management:
  health:
    probes:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,shutdown
endpoint:
  health:
    show-details: always

server:
  shutdown: graceful
  error:
    include-message: always
    whitelabel.enabled: false


#########################################################################
#logging

logging:
  level:
    org.springframework.data: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


