spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://assist-postgresql.postgres.database.azure.com:5432/assist-central-db?sslmode=require
    username: assistadmin@assist-postgresql
    password: QbZ2NmQvcjNz7ZF
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
      show-sql: true

server:
  shutdown: graceful


#########################################################################
#logging

logging:
  level:
    org.springframework.data: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


